### ISSUE TITLE
Target application shuts down after injection

### ISSUE THREAD

**Issue by DrJedikiah** [mactec0/Kernelmode-manual-mapping-through-IAT#1]
Test dll is x64, injector is built as x64 and nothing changed in the source code.

It says injection successful and then target application freezes and crashes. In this case notepad.

**Comment by mactec0** [comment]
Since you have provided so little information about the crash, I'm unable to tell you exactly where the problem is. My guess is that it occurs because you've selected wrong settings in the project properties and it's not getting compiled statically or somehow the restore function gets optimized.
I've uploaded new release with all the project files needed, use them and compile everything as X64-Release. It should solve your problem. 
And next time I suggest you to try debugging first(for example with x64dbg) in order to track down the issue or to at least get a bit more information about the problem.

**Comment by DrJedikiah** [comment]
I've checked that function, it wasn't inlined or included and sorry I should've debugged. I'll try with your update thanks. I use this to make sure it's included `#pragma comment(linker, "/INCLUDE:" __FUNCDNAME__)`

**Comment by DrJedikiah** [comment]
Problem solved, sorry for disturbing. Turns out problem was in my dll.
