### ISSUE TITLE
Application closes after injection

### ISSUE THREAD

**Issue by poorcuz** [mactec0/Kernelmode-manual-mapping-through-IAT#4]
Alright, compiled this and also compiled the target DLL. Both x64 obviously.
Whenever injecting (tested both usermode & kernel mode), the target application just shuts down.
I've disabled optimization on the target DLL.

**Comment by mactec0** [comment]
I'm not able to tell you exactly what's wrong because you have given no information about the crash itself. Attach the debugger to the target process to see what exactly happens.

I can think of 2 things that might be the issue. 
1. DLL is not compiled statically and it crashes after trying to call some external dependencies 
2. You are skipping this Pause, before the TranslateMessage gets called: 
`LOG("Injected successfully!");`
`system("Pause");`
which later leads to the stub code trying to write to read only memory, here:
`0000002A mov [rax],rdx`

I've updated project files and uploaded them to the [releases](https://github.com/mactec0/Kernelmode-manual-mapping-through-IAT/releases), check if the issue still exist after compiling using them.

**Comment by poorcuz** [comment]
Yeah, I missed the pause.
I've compiled it using your project and put the pause back in place and it worked completely fine!
Thanks!
